# GitHub Sponsors and funding options for react-usekit
# You can uncomment and customize these when you're ready to accept funding

# github: [brijeshkumaryadav]
# patreon: your_patreon_username
# open_collective: react-usekit
# ko_fi: your_kofi_username
# tidelift: npm/react-usekit
# community_bridge: react-usekit
# liberapay: your_liberapay_username
# issuehunt: brijeshkumaryadav
# otechie: your_otechie_username
# lfx_crowdfunding: react-usekit
# custom: ["https://paypal.me/yourusername", "https://buymeacoffee.com/yourusername"]
