blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/brijeshb42/react-usekit/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://react-usekit.com
    about: Read the comprehensive documentation and guides
