name: Documentation Issue
description: Report an issue with documentation
title: '[Docs]: '
labels: ['documentation', 'triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      multiple: false
      options:
        - Website/Main Docs
        - Hook Documentation
        - Utility Documentation
        - CLI Documentation
        - README/Getting Started
        - API Reference
        - Examples/Tutorials
    validations:
      required: true

  - type: input
    id: page-url
    attributes:
      label: Page URL (if applicable)
      description: Link to the documentation page with the issue
      placeholder: https://www.react-usekit.com/docs/hooks/use-local-storage

  - type: textarea
    id: issue-description
    attributes:
      label: What's wrong with the documentation?
      description: Describe the issue with the current documentation
      placeholder: The example code doesn't work, there's a typo, missing information, etc.
    validations:
      required: true

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: How do you think this should be fixed?
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
