name: Feature Request
description: Suggest an idea for this project
title: "[feat]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! We appreciate your input.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: Tell us about your feature request
      placeholder: "I think this feature would be great because..."
      value: "Describe your feature request..."
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: What type of feature is this?
      multiple: false
      options:
        - New React Hook
        - New Utility Function
        - CLI Enhancement
        - Documentation Improvement
        - Developer Experience
        - Other
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, code examples, or screenshots about the feature request here.

  - type: checkboxes
    id: before-submitting
    attributes:
      label: Before submitting
      description: By submitting this issue, you agree to follow our Contributing Guidelines.
      options:
        - label: I've made research efforts and searched the documentation
          required: true
        - label: I've searched for existing issues
          required: true
